name: Running Benchmarks JMH

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        distributions: [ 'zulu', 'temurin', 'microsoft', 'corretto','oracle' ]
        java: [ 8, 11, 17 ]
    name: Java ${{ matrix.java }} ${{ matrix.distributions }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: |
          mvn -ntp clean package
          git pull
          git add .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: csv adding back to repo [skip ci] another test
