name: Running Benchmarks JMH

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17]
    name: Java ${{ matrix.java }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: |
          mvn -ntp clean package
          git add .
          git commit -m "generated ${{ matrix.java }}"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: csv adding back to repo [skip ci] another test