name: Running Benchmarks JMH
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        distribution: [ 'semeru', 'adopt', 'zulu', 'temurin', 'microsoft', 'corretto','oracle' ]
        java: [ 17 ]
    name: Java ${{ matrix.java }} ${{ matrix.distribution }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - run: |
          mvn -ntp clean package
          rm -rf target
          git add -f .          
          git pull
#          mvn -ntp -Dtest=PrintSome test
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: adding back to repo [skip ci] another test
